### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'

### ISSUE THREAD

**Issue by xuxping** [mkavim/finetune_bert#1]
测试时出现👇问题
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "finetune_bert.py", line 14, in <module>
    from keras_bert import Tokenizer
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras_bert/__init__.py", line 1, in <module>
    from .bert import *
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras_bert/bert.py", line 2, in <module>
    from keras_pos_embd import PositionEmbedding
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras_pos_embd/__init__.py", line 1, in <module>
    from .pos_embd import PositionEmbedding
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras_pos_embd/pos_embd.py", line 1, in <module>
    from .backend import keras
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras_pos_embd/backend.py", line 12, in <module>
    import keras
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/xuxiaoping/anaconda3/envs/py35/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 54, in <module>
    get_graph = tf_keras_backend.get_graph
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'
```

**Comment by xuxping** [comment]
采用tensorflow作为后端，需要设置`os.environ['TF_KERAS'] = '1'`
